# DATA  690 - Lecture 10 Assignment

## Creating a sample code of partitioning. Use 5 as k argumemnt.

In [117]:
import numpy as np

In [118]:
x=np.random.randint(low=1, high=20, size=10)
print('\nGiven Array is : ', x)
print('\nPartitioned Array is : ', np.partition(x,5))


Given Array is :  [17  2 18 14 16  6 12 19  8 12]

Partitioned Array is :  [ 2  6  8 12 12 14 16 19 18 17]


## Sample Structure Array 

In [119]:
data = np.zeros(10, dtype={'names':('orderdate', 'orderamount', 'ordernumber', 'ordername'),
                          'formats':('U8', 'f8', 'i4',  'U20')})

In [123]:
OrderDate = ["1/2/2021", "4/3/2021","2/2/2021" ,"3/3/2021", "8/4/2021","6/3/2021", "2/5/2021", "6/2/2021", "1/5/2021","8/2/2021"]
OrderAmount = np.random.randint(low=50, high=100, size=10)
OrderNumber = [101,102,103,104,105,106,107,108,109,110]
OrderName = ["Mike","John","Rick","Milton","Juce","Jally","Cosher","Pary","Nelson","Miroz"]


In [124]:
data ["orderdate"]=OrderDate
data["orderamount"]= OrderAmount
data["ordernumber"]= OrderNumber
data["ordername"] = OrderName

In [125]:
print(data)

[('1/2/2021', 91., 101, 'Mike') ('4/3/2021', 63., 102, 'John')
 ('2/2/2021', 97., 103, 'Rick') ('3/3/2021', 75., 104, 'Milton')
 ('8/4/2021', 90., 105, 'Juce') ('6/3/2021', 88., 106, 'Jally')
 ('2/5/2021', 82., 107, 'Cosher') ('6/2/2021', 51., 108, 'Pary')
 ('1/5/2021', 72., 109, 'Nelson') ('8/2/2021', 55., 110, 'Miroz')]


In [126]:
data[data['ordernumber'] < 105]

array([('1/2/2021', 91., 101, 'Mike'), ('4/3/2021', 63., 102, 'John'),
       ('2/2/2021', 97., 103, 'Rick'), ('3/3/2021', 75., 104, 'Milton')],
      dtype=[('orderdate', '<U8'), ('orderamount', '<f8'), ('ordernumber', '<i4'), ('ordername', '<U20')])

## Generating the array

In [127]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(10, 10))

In [128]:
print(x)

[[5 0 3 3 7 9 3 5 2 4]
 [7 6 8 8 1 6 7 7 8 1]
 [5 9 8 9 4 3 0 3 5 0]
 [2 3 8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7 2 0]
 [0 4 5 5 6 8 4 1 4 9]
 [8 1 1 7 9 9 3 6 7 2]
 [0 3 5 9 4 4 6 4 4 3]
 [4 4 8 4 3 7 5 5 0 1]
 [5 9 3 0 5 0 1 2 4 2]]


In [129]:
a1 = np.array([0, 2, 4,6,8])
a2 = np.array([0,3, 4, 6, 7])
x[a1[:, np.newaxis], a2]

array([[5, 3, 7, 3, 5],
       [5, 9, 4, 0, 3],
       [9, 4, 7, 2, 7],
       [8, 7, 9, 3, 6],
       [4, 4, 3, 5, 5]])