#### 1. Import the numpy package

In [1]:
!pip install numpy

In [2]:
import numpy as np

#### 2. Create a 1-dimensional NumPy array with size of 10 filled with value 0

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 3. Create a 1-dimensional NumPy array with size of 10 filled with value 1

In [4]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 4. Create a 1-dimensional NumPy array with size of 10 filled with value 3.14

In [5]:
np.full(10, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

#### 5. Create a 2-dimensional NumPy array with shape (5,5) filled with value 3.14

In [6]:
a=np.full((5, 5), 3.14)
a

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

#### 6. Calculate the total bytes used by the array in #5

In [7]:
print(a.nbytes, 'bytes')

200 bytes


#### 7. Create a NumPy array with values in range from 21 to 100

In [8]:
a=np.arange(21,100)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
       89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 8. Reverse the array in #7

In [9]:
a[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

#### 9. Create a 10x10 identity matrix

In [10]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

#### 10. Create a 20x20 NumPy array with random values and find the minimum and maximum values

In [16]:
np.random.seed(10)
a = np.random.random((20,20))
print(a)
print('\nMinimum value is : ', a.min())
print('\nMaximum value is : ', a.max())

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
  0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
  0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
  0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317 0.43401399
  0.61776698 0.51313824 0.65039718 0.60103895 0.8052232  0.52164715
  0.90864888 0.31923609 0.09045935 0.30070006 0.11398436 0.82868133
  0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264 0.75464769
  0.29596171 0.88393648 0.32551164 0.1650159  0.39252924 0.09346037
  0.82110566 0.15115202 0.38411445 0.94426071 0.98762547 0.45630455
  0.82612284 0.25137413]
 [0.59737165 0.90283176 0.53455795 0.59020136 0.03928177 0.35718176
  0.07961309 0.30545992 0.33071931 0.7738303  0.03995921 0.42949218
  0.31492687 0.63649114 0.34634715 0.04309736 0.87991517 0.76324059
  0.87809664 0.41750914]
 [0.60557756 0.51346663 0.59783665 0.26221566 0.30087131 0.02539978
  0.30306256 0.2

#### 11. Create a 6x6 NumPy array with random values. Split the array evenly vertically

In [14]:
np.random.seed(10)
a = np.random.random((6,6))
print(a)
upper, lower = np.vsplit(a, [3])
print('\n',upper)
print('\n',lower)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607]
 [0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006]]

 [[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607]]

 [[0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006]]


#### 12. For the same arry in #11, split the array evenly horizontally

In [15]:
left, right = np.hsplit(a, [3])
print('\n',left)
print('\n',right)


 [[0.77132064 0.02075195 0.63364823]
 [0.19806286 0.76053071 0.16911084]
 [0.00394827 0.51219226 0.81262096]
 [0.91777412 0.71457578 0.54254437]
 [0.44183317 0.43401399 0.61776698]
 [0.8052232  0.52164715 0.90864888]]

 [[0.74880388 0.49850701 0.22479665]
 [0.08833981 0.68535982 0.95339335]
 [0.61252607 0.72175532 0.29187607]
 [0.14217005 0.37334076 0.67413362]
 [0.51313824 0.65039718 0.60103895]
 [0.31923609 0.09045935 0.30070006]]
